create=cmd /c mkdir ${project_path}
explorer=explorer ${project_path} ${remaining_args}
vscode=code.CMD ${project_path} ${remaining_args}
code=vscode
term=wt --focus -d ${project_path} ${remaining_args}