explorer=explorer ${project_path} ${remaining_args}
vscode=code.CMD ${project_path} ${remaining_args}
code=vscode
powershell=powershell -WorkingDirectory ${project_path} ${remaining_args}
term=powershell