#Thanks https://dev.to/rahul_suryash/steps-to-build-binary-executables-for-python-code-with-github-actions-4k92
#TODO: build exe only on .py modification

name: Build and Release Executables

on:
  push:
    branches:
      - 'main' 
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main.exe dist/p-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/main dist/p-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/main dist/p-macos
          fi
          mv commands.conf home.conf readme.md dist/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: p-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux/Mac)
        run: chmod +x p-* || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          files: |
            p-linux
            p-windows.exe
            p-macos
